### ISSUE TITLE
How to Set Animation Loop?

### ISSUE THREAD

**Issue by JusamLiu** [instance-id/ElementAnimationToolkit#1]
Hello, I want to know how to set animation loop?

**Comment by instance-id** [comment]
If you take a look at the file [ContinuousAnimations.cs](https://github.com/instance-id/ElementAnimationToolkit/blob/88c52001d8c5ecd8e65db2ad1e6c136552d1a82c/Assets/instance.id/ElementAnimationToolkit/Runtime/Scripts/Extensions/Animations/ContinuousAnimations.cs#L181) You can see a fairly complex one, which is the mouse hover animations in the example.

A more simple example would be to use something like the following:
```cs
// -- This would be put somewhere in your editor/inspector hierarchy
myVisualElement.schedule.Execute(AnimationToLoop).Every(10).StartingIn(0);

// -- This would go somewhere in your editor/inspector as well
public void AnimationToLoop(()
{
	// -- My animation goes here
}
```

This takes the element you want to animate (myVisualElement) and then creates a scheduler on it using the Every() function, which would then continually loop. If you want to be able to control it, though, you will need to keep track of the scheduler via a `IVisualElementScheduledItem myScheduledItem;` like this:

```cs

private IVisualElementScheduledItem myScheduledItem;

// -- elsewhere
myScheduledItem = myVisualElement.schedule.Execute(AnimationToLoop).Every(10).StartingIn(0);

// -- This will then let you call things such as:
myScheduledItem.Pause();
myScheduledItem.Resume();
```
Thanks,
-id
